/*
 * DO NOT EDIT THIS FILE. Generated by checkmk.
 * Edit the original source file "conv_test.check" instead.
 */

#include <check.h>

#include "../s21_decimal.h"

START_TEST(from_int_to_dec) {
  s21_decimal res_dec, correct_result;
  init_dec(&res_dec), init_dec(&correct_result);
  int signed_integer = 0, res_of_conv = 0;

  // check NULL
  res_of_conv = s21_from_int_to_decimal(signed_integer, NULL);
  ck_assert_int_eq(res_of_conv, 1);

  // check 0
  res_of_conv = s21_from_int_to_decimal(signed_integer, &res_dec);
  str_to_dec("0", &correct_result, 0);
  ck_assert_int_eq(res_of_conv, 0);
  ck_assert_int_eq(s21_is_equal(correct_result, res_dec), 0);

  // check 123456789
  signed_integer = 123456789;
  res_of_conv = s21_from_int_to_decimal(signed_integer, &res_dec);
  str_to_dec("111010110111100110100010101", &correct_result, 0);
  ck_assert_int_eq(res_of_conv, 0);
  ck_assert_int_eq(s21_is_equal(correct_result, res_dec), 0);

  // check -123456789
  signed_integer = -123456789;
  res_of_conv = s21_from_int_to_decimal(signed_integer, &res_dec);
  str_to_dec("-111010110111100110100010101", &correct_result, 0);
  ck_assert_int_eq(res_of_conv, 0);
  ck_assert_int_eq(s21_is_equal(correct_result, res_dec), 0);
}
END_TEST

START_TEST(from_float_to_dec) {
  s21_decimal res, correct_result;
  init_dec(&res), init_dec(&correct_result);
  int res_of_conv = 0;
  float fl_val = 0;

  // check NULL
  res_of_conv = s21_from_float_to_decimal(fl_val, NULL);
  ck_assert_int_eq(res_of_conv, 1);

  // check NaN
  fl_val = S21_NANF;
  res_of_conv = s21_from_float_to_decimal(fl_val, &res);
  ck_assert_int_eq(res_of_conv, 1);
  ck_assert_int_eq(res.value_type, s21_NAN);

  // check INF
  fl_val = S21_INFL;
  res_of_conv = s21_from_float_to_decimal(fl_val, &res);
  ck_assert_int_eq(res_of_conv, 1);
  ck_assert_int_eq(res.value_type, s21_INFINITY);

  // check -INF
  fl_val = -INFINITY;
  res_of_conv = s21_from_float_to_decimal(fl_val, &res);
  ck_assert_int_eq(res_of_conv, 1);
  ck_assert_int_eq(res.value_type, s21_NEGATIVE_INFINITY);

  // check 0
  fl_val = 0;
  res_of_conv = s21_from_int_to_decimal(fl_val, &res);
  str_to_dec("0", &correct_result, 0);
  ck_assert_int_eq(res_of_conv, 0);
  ck_assert_int_eq(s21_is_equal(correct_result, res), 0);
}

START_TEST(from_dec_to_int) {
  s21_decimal dec;
  init_dec(&dec);
  int res_of_conv = 0, converted_int = 0;

  // check NULL
  res_of_conv = s21_from_decimal_to_int(dec, NULL);
  ck_assert_int_eq(res_of_conv, 1);

  // check INF
  dec.value_type = s21_INFINITY;
  res_of_conv = s21_from_decimal_to_int(dec, &converted_int);
  ck_assert_int_eq(res_of_conv, 1);
}
END_TEST

START_TEST(from_dec_to_float) {
  s21_decimal dec;
  init_dec(&dec);
  int res_of_conv = 0;
  float converted_fl = 0, correct_result = 0;

  // check NULL
  res_of_conv = s21_from_decimal_to_float(dec, NULL);
  ck_assert_int_eq(res_of_conv, 1);

  // check INF
  dec.value_type = s21_INFINITY;
  res_of_conv = s21_from_decimal_to_float(dec, &converted_fl);
  ck_assert_int_eq(res_of_conv, 1);
  ck_assert_int_eq(1, isinf(converted_fl));

  // check NEG_INF
  dec.value_type = s21_NEGATIVE_INFINITY;
  res_of_conv = s21_from_decimal_to_float(dec, &converted_fl);
  ck_assert_int_eq(res_of_conv, 1);
  ck_assert_int_eq(1, isinf(-converted_fl));

  // check NaN
  dec.value_type = s21_NAN;
  res_of_conv = s21_from_decimal_to_float(dec, &converted_fl);
  ck_assert_int_eq(res_of_conv, 1);
  ck_assert_int_eq(1, isnan(converted_fl));

  init_dec(&dec);
  // check max 79228162514264337593543950335
  correct_result = 79228162514264337593543950335.;
  str_to_dec(
      "1111111111111111111111111111111111111111111111111111111111111111111111"
      "11111111111111111111111111",
      &dec, 0);
  res_of_conv = s21_from_decimal_to_float(dec, &converted_fl);
  ck_assert_float_eq(converted_fl, correct_result);
  ck_assert_int_eq(res_of_conv, 0);
  init_dec(&dec);

  // check min 1e-28
  correct_result = 1e-28;
  str_to_dec("1", &dec, 28);
  res_of_conv = s21_from_decimal_to_float(dec, &converted_fl);
  ck_assert_float_eq(converted_fl, correct_result);
  ck_assert_int_eq(res_of_conv, 0);
  init_dec(&dec);

  // check precise 1.234567
  correct_result = 1.234567;
  str_to_dec("100101101011010000111", &dec, 6);
  res_of_conv = s21_from_decimal_to_float(dec, &converted_fl);
  ck_assert_float_eq(converted_fl, correct_result);
  ck_assert_int_eq(res_of_conv, 0);
  init_dec(&dec);
}
END_TEST

START_TEST(div_common_values) {
  s21_decimal dec1, dec2, result, correct_result;
  init_dec(&correct_result);
  init_dec(&result);
  init_dec(&dec1);
  init_dec(&dec2);

  str_to_dec("11001010", &dec1, 0);
  str_to_dec("11001010", &dec2, 0);
  result = s21_div(dec1, dec2);
  str_to_dec("1", &correct_result, 0);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  // 4
  str_to_dec("100", &dec1, 0);
  // 3
  str_to_dec("11", &dec2, 0);
  result = s21_div(dec1, dec2);
  // 1.3333333333333333333333333333
  str_to_dec(
      "1010110001010100010011001010000101001011011100000000110010110000010101"
      "01"
      "0101010101010101010101",
      &correct_result, 28);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  // 123515
  str_to_dec("11110001001111011", &dec1, 0);
  // 11
  str_to_dec("1011", &dec2, 0);
  result = s21_div(dec1, dec2);
  // 11228.636363636363636363
  str_to_dec(
      "1001000100100000011100001111001111100110100111100111111110111111011001"
      "10"
      "1110100010111010001100",
      &correct_result, 24);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);
}
END_TEST

START_TEST(div_uncommon_values) {
  s21_decimal dec1, dec2, result, correct_result;
  init_dec(&correct_result);
  str_to_dec("1010", &dec1, 0);
  // 0.1
  str_to_dec("1", &dec2, 1);
  result = s21_div(dec1, dec2);
  // 112286.36363636363636363
  str_to_dec("1100100", &correct_result, 0);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);
  // 120.071235
  str_to_dec("111001010000010010001000011", &dec1, 6);
  // 0.123541
  str_to_dec("11110001010010101", &dec2, 6);
  result = s21_div(dec1, dec2);
  // 971.9140609190471179608389118
  str_to_dec(
      "1111101100111011111000001010000101000101010000110101110101001101000111"
      "11"
      "001011111010111111110",
      &correct_result, 25);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);
  // 11228.636363636363636363
  str_to_dec(
      "1001000100100000011100001111001111100110100111100111111110111111011001"
      "10"
      "1110100010111010001011",
      &dec1, 24);
  // 0.1
  str_to_dec("1", &dec2, 1);
  result = s21_div(dec1, dec2);

  // 112286.36363636363636363
  str_to_dec(
      "1001000100100000011100001111001111100110100111100111111110111111011001"
      "10"
      "1110100010111010001011",
      &correct_result, 23);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  // 112286363636363636.36363
  str_to_dec(
      "1001000100100000011100001111001111100110100111100111111110111111011001"
      "10"
      "1110100010111010001011",
      &dec1, 5);
  // 11
  str_to_dec("1011", &dec2, 0);

  result = s21_div(dec1, dec2);

  // 10207851239669421487603.305784

  // 102078512396694214.87602727272
  str_to_dec(
      "0010000011111011101111001001010010000101110111100011010001001110011010"
      "00"
      "110101111100110100111000",
      &correct_result, 6);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  // #1
  // 112286.36363636363636363
  str_to_dec(
      "1001100000101101001010001000000000110111001011001101011"
      "1100010111010001011",
      &dec1, 17);
  // 4.16787847
  str_to_dec("11000110101111010110110000111", &dec2, 8);

  result = s21_div(dec1, dec2);

  // 26940.89197767890683329593341
  str_to_dec(
      "100010110100011111111001010000001101111100101010"
      "01110011100010001001110001010011111111111101",
      &correct_result, 23);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  //  #2
  // 135521
  str_to_dec("100001000101100001", &dec1, 0);
  // 3724292940501892409235
  str_to_dec(
      "11001001111001001111001001111001001111001001111001"
      "0011110010011110010011",
      &dec2, 0);

  result = s21_div(dec1, dec2);

  // 0.0000000000000000363883835576
  str_to_dec("101010010111001001010101011000010111000", &correct_result, 28);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  // #3
  // 135521
  str_to_dec("100001000101100001", &dec1, 7);
  // 3724292940501892409235
  str_to_dec(
      "1100100111100100111100100111100100111100100111"
      "10010011110010011110010011",
      &dec2, 28);

  result = s21_div(dec1, dec2);

  // 36388.383557641667818989545662
  str_to_dec(
      "111010110010011110000111111000101010010010100001100"
      "10100001111100111000100111111110100010111110",
      &correct_result, 24);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  // #4
  // 24560730379421944653998624.602
  str_to_dec(
      "100111101011100001010001111010111000010100011110101110"
      "00010100011110101110000101000111101011010",
      &dec1, 3);
  // 31.7
  str_to_dec("100111101", &dec2, 1);

  result = s21_div(dec1, dec2);

  // 774786447300376802965256.29659
  str_to_dec(
      "111110100101100011010101001100101110000010000001001101100001101101110101"
      "000110010000100011011011",
      &correct_result, 5);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  // #5
  // 0.0000000000000000009
  str_to_dec("1001", &dec1, 19);
  // 0,000000000000000000000009
  str_to_dec("1001", &dec2, 24);

  result = s21_div(dec1, dec2);

  // 100000
  str_to_dec("11000011010100000", &correct_result, 0);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  // #6
  // 0,0000000000000000000000095642
  str_to_dec("10111010110011010", &dec1, 28);
  // 0,0000000000000000000000112
  str_to_dec("1110000", &dec2, 25);

  result = s21_div(dec1, dec2);

  // 0.8539464285714285714285714286
  str_to_dec(
      "1101110010111101011011110011010000101100011010111110111"
      "11000010110011011101101101101101101110",
      &correct_result, 28);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  // #7
  // 0,0000000000000000000000095642
  str_to_dec("10111010110011010", &dec1, 28);
  // 112000
  str_to_dec("11011010110000000", &dec2, 0);

  result = s21_div(dec1, dec2);

  // 0.0000000000000000000000000001
  str_to_dec("1", &correct_result, 28);
  // print_dec(result);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  // #7
  // 0,0000000000000000000000095642
  str_to_dec("10111010110011010", &dec1, 28);
  // 272000
  str_to_dec("1000010011010000000", &dec2, 0);

  result = s21_div(dec1, dec2);

  // 0
  str_to_dec("0", &correct_result, 0);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  // #8
  // 0,0000000000000000000000095642
  str_to_dec("10111010110011010", &dec1, 28);
  // 0.0000000000000000000000000002
  str_to_dec("10", &dec2, 28);

  result = s21_div(dec1, dec2);

  // 47821
  str_to_dec("1011101011001101", &correct_result, 0);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  // #9
  // 0,0000000000000000000000095642
  str_to_dec("10111010110011010", &dec1, 28);
  // 0.8539464285714285714285714286
  str_to_dec(
      "1101110010111101011011110011010000101100011010111110111"
      "11000010110011011101101101101101101110",
      &dec2, 28);

  result = s21_div(dec1, dec2);

  // 0.0000000000000000000000112
  str_to_dec("1110000", &correct_result, 25);
  // print_dec(result);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  // #10
  // 24560730379421944653998624.602
  str_to_dec(
      "100111101011100001010001111010111000010100011110101110"
      "00010100011110101110000101000111101011010",
      &dec1, 3);
  // 792281625142643375935439.50329
  str_to_dec(
      "1111111111111111111111111111111111111111111111111111"
      "11111111111111111111111111111111111111111001",
      &dec2, 5);

  result = s21_div(dec1, dec2);

  // 31
  str_to_dec("11111", &correct_result, 0);
  // print_dec(result);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);
}
END_TEST

START_TEST(mod_common_values) {
  s21_decimal dec1, dec2, result, correct_result;
  init_dec(&correct_result);
  init_dec(&result);
  init_dec(&dec1);
  init_dec(&dec2);

  // 202
  str_to_dec("11001010", &dec1, 0);
  // 202
  str_to_dec("11001010", &dec2, 0);
  // 0
  init_dec(&result);
  result = s21_mod(dec1, dec2);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);
  // 203
  str_to_dec("11001011", &dec1, 0);
  // 202
  str_to_dec("11001010", &dec2, 0);
  // 1
  str_to_dec("1", &correct_result, 0);
  result = s21_mod(dec1, dec2);

  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  // 403

  str_to_dec("110010011", &dec1, 0);

  // 202
  str_to_dec("11001010", &dec2, 0);
  // 201
  str_to_dec("11001001", &correct_result, 0);
  result = s21_mod(dec1, dec2);

  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  // 54195595155
  str_to_dec("110010011110010011110010011110010011", &dec1, 0);
  // 10
  str_to_dec("1010", &dec2, 0);
  // 5
  str_to_dec("101", &correct_result, 0);
  result = s21_mod(dec1, dec2);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  // 54195595155
  str_to_dec("110010011110010011110010011110010011", &dec1, 0);
  // 1000
  str_to_dec("1111101000", &dec2, 0);
  // 155
  str_to_dec("10011011", &correct_result, 0);
  result = s21_mod(dec1, dec2);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  // 3724292940501892409235
  str_to_dec(
      "1100100111100100111100100111100100111100100111100100111100100111100100"
      "1"
      "1",
      &dec1, 0);
  // 135521
  str_to_dec("100001000101100001", &dec2, 0);
  // 100360
  str_to_dec("11000100000001000", &correct_result, 0);
  result = s21_mod(dec1, dec2);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  // 3905204194379712334906604703
  str_to_dec(
      "1100100111100100111100100111100100111100100111100100111100100111100100"
      "11"
      "10010011110010011111",
      &dec1, 0);
  // 135521
  str_to_dec("100001000101100001", &dec2, 0);
  // 112657
  str_to_dec("11011100000010001", &correct_result, 0);
  result = s21_mod(dec1, dec2);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);
}
END_TEST

START_TEST(mod_uncommon_values) {
  s21_decimal dec1, dec2, result, correct_result;
  init_dec(&correct_result);
  init_dec(&result);
  init_dec(&dec1);
  init_dec(&dec2);

  // 3905204194379712334906604703
  str_to_dec("111111111111111111111111111111111", &dec1, 0);
  // 135521
  str_to_dec("11111111111111111111111111111111", &dec2, 0);
  // 112657
  str_to_dec("1", &correct_result, 0);
  result = s21_mod(dec1, dec2);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  // 792281625
  str_to_dec("101111001110010100001000011001", &dec1, 0);
  // 4.951760157141521
  str_to_dec("10001100101111001100110000001001011011110101000010001", &dec2,
             15);
  result = s21_mod(dec1, dec2);
  // 4.809116797141521
  str_to_dec("10001000101011101110111000010011000001000001000010001",
             &correct_result, 15);

  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  // 54375684.5645934765284
  str_to_dec(
      "111010111101000100100011000100010101011110000110110100010010011100100",
      &dec1, 13);
  // 4.951760157141521
  str_to_dec("10001100101111001100110000001001011011110101000010001", &dec2,
             15);
  result = s21_mod(dec1, dec2);

  // 0.2346895488226780
  // 0.234689548822678

  str_to_dec("110101010111001011101011001100001010100010010110",
             &correct_result, 15);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  // 54375684.5645934765284
  str_to_dec(
      "111010111101000100100011000100010101011110000110110100010010011100100",
      &dec1, 13);
  // 11.9888888888888888
  str_to_dec("110101001111011100100111100101010101111010000111000111000", &dec2,
             16);
  result = s21_mod(dec1, dec2);
  // 7.0757045880426672
  str_to_dec("11111011011000010010100010001001000011110001000010110000",
             &correct_result, 16);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  // 99999,99999999999999999999999
  // 99999.99999999999999999999999
  str_to_dec(
      "1000000100111111001110010111100011111000100101000"
      "000100110000100001111111111111111111111111111",
      &dec1, 23);
  // 0,000000000000000000000009
  str_to_dec("1001", &dec2, 24);
  result = s21_mod(dec1, dec2);

  // 0.000000000000000000000000
  init_dec(&correct_result);
  //   correct_result.value_type = s21_INFINITY;
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  // 99999,99999999999999999999999
  str_to_dec(
      "1000000100111111001110010111100011111000100101000"
      "000100110000100001111111111111111111111111111",
      &dec1, 23);
  // 0,02
  str_to_dec("10", &dec2, 2);
  result = s21_mod(dec1, dec2);
  // 0.01999999999999999999999

  str_to_dec(
      "1101100011010111001001101011011100010111011110100111111111111111111111"
      "1",
      &correct_result, 23);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  // 99999,99999999999999999999999
  str_to_dec("1001", &dec1, 23);
  // 0,02
  str_to_dec("10", &dec2, 2);
  result = s21_mod(dec1, dec2);
  // 0.01999999999999999999999

  str_to_dec("1001", &correct_result, 23);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  // #1
  // 112286.36363636363636363
  str_to_dec(
      "1001100000101101001010001000000000110111001011001101011"
      "1100010111010001011",
      &dec1, 17);
  // 4.16787847
  str_to_dec("11000110101111010110110000111", &dec2, 8);

  result = s21_mod(dec1, dec2);

  // 3.71765456363636363
  str_to_dec("10100101000110001101011011001111110010100001100011010001011",
             &correct_result, 17);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  // #2
  // 3724292940501892409235
  str_to_dec(
      "11001001111001001111001001111001001111001001111001"
      "0011110010011110010011",
      &dec1, 0);
  // 135521
  str_to_dec("100001000101100001", &dec2, 0);

  result = s21_mod(dec1, dec2);

  // 100360
  str_to_dec("11000100000001000", &correct_result, 0);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  // #3
  // 0.0135521
  str_to_dec("100001000101100001", &dec1, 7);
  // 0.0000003724292940501892409235
  str_to_dec(
      "1100100111100100111100100111100100111100100111"
      "10010011110010011110010011",
      &dec2, 28);

  result = s21_mod(dec1, dec2);

  // 0.0000001428481017139012756820
  str_to_dec(
      "10011010111000000101000000011001010101111001111100010101110010101010100",
      &correct_result, 28);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  // #4
  // 24560730379421944653998624.602
  str_to_dec(
      "100111101011100001010001111010111000010100011110101110"
      "00010100011110101110000101000111101011010",
      &dec1, 3);
  // 31.7
  str_to_dec("100111101", &dec2, 1);

  result = s21_mod(dec1, dec2);

  // 9.402
  str_to_dec("10010010111010", &correct_result, 3);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  // #5
  // 0.0000000000000000009
  str_to_dec("1001", &dec1, 19);
  // 0,000000000000000000000009
  str_to_dec("1001", &dec2, 24);

  result = s21_mod(dec1, dec2);

  // 0
  str_to_dec("0", &correct_result, 0);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  // #6
  // 0,0000000000000000000000095642
  str_to_dec("10111010110011010", &dec1, 28);
  // 0,0000000000000000000000112
  str_to_dec("1110000", &dec2, 25);

  result = s21_mod(dec1, dec2);

  // 0,0000000000000000000000095642
  str_to_dec("10111010110011010", &correct_result, 28);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  // #7
  // 112000
  str_to_dec("11011010110000000", &dec1, 0);
  // 0,0000000000000000000000095642
  str_to_dec("10111010110011010", &dec2, 28);

  result = s21_mod(dec1, dec2);

  // 0.0000000000000000000000049998
  str_to_dec("1100001101001110", &correct_result, 28);
  // print_dec(result);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  // #8
  // 272000
  str_to_dec("1000010011010000000", &dec1, 0);
  // 0,0000000000000000000000095642
  str_to_dec("10111010110011010", &dec2, 28);

  result = s21_mod(dec1, dec2);

  // 0.0000000000000000000000053108
  str_to_dec("1100111101110100", &correct_result, 28);
  // print_dec(result);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  // #9
  // 0,0000000000000000000000095642
  str_to_dec("10111010110011010", &dec1, 28);
  // 0.0000000000000000000000000002
  str_to_dec("10", &dec2, 28);

  result = s21_mod(dec1, dec2);

  // 0
  str_to_dec("0", &correct_result, 0);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  // #10
  // 0.8539464285714285714285714286
  str_to_dec(
      "1101110010111101011011110011010000101100011010111110111"
      "11000010110011011101101101101101101110",
      &dec1, 28);
  // 0,0000000000000000000000095642
  str_to_dec("10111010110011010", &dec2, 28);

  result = s21_mod(dec1, dec2);

  // 0.0000000000000000000000068316
  str_to_dec("10000101011011100", &correct_result, 28);
  // print_dec(result);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  // #11
  // 24560730379421944653998624.602
  str_to_dec(
      "100111101011100001010001111010111000010100011110101110"
      "00010100011110101110000101000111101011010",
      &dec1, 3);
  // 792281625142643375935439.50329
  str_to_dec(
      "1111111111111111111111111111111111111111111111111111"
      "11111111111111111111111111111111111111111001",
      &dec2, 5);

  result = s21_mod(dec1, dec2);

  // 0.00001
  str_to_dec("1", &correct_result, 5);
  // print_dec(result);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);
}
END_TEST

START_TEST(eq_funcs_test) {
  s21_decimal dec1, dec2;
  init_dec(&dec1);
  init_dec(&dec2);
  dec1.bits[0] = 1325411;
  dec2.bits[0] = 1325411;
  dec1.bits[1] = 121;
  dec2.bits[1] = 121;
  dec1.bits[2] = 213;
  dec2.bits[2] = 213;

  ck_assert_int_eq(s21_is_equal(dec1, dec2), 0);
  ck_assert_int_eq(s21_is_not_equal(dec1, dec2), 1);

  dec2.bits[3] += SIGN_MINUS;

  ck_assert_int_eq(s21_is_equal(dec1, dec2), 1);
  ck_assert_int_eq(s21_is_not_equal(dec1, dec2), 0);

  dec1.bits[3] += SIGN_MINUS;

  ck_assert_int_eq(s21_is_equal(dec1, dec2), 0);
  ck_assert_int_eq(s21_is_not_equal(dec1, dec2), 1);

  dec2.bits[0] = 132541;

  ck_assert_int_eq(s21_is_equal(dec1, dec2), 1);
  ck_assert_int_eq(s21_is_not_equal(dec1, dec2), 0);

  dec1.bits[0] = 2147483647;
  dec2.bits[0] = 2147483647;
  dec1.bits[1] = 0;
  dec2.bits[1] = 2147483647;
  dec1.bits[2] = 2147483647;
  dec2.bits[2] = 2147483647;

  ck_assert_int_eq(s21_is_equal(dec1, dec2), 1);
  ck_assert_int_eq(s21_is_not_equal(dec1, dec2), 0);

  str_to_dec("-1010011110", &dec1, 0);
  str_to_dec("-1000011", &dec2, 0);
  ck_assert_int_eq(s21_is_equal(dec1, dec2), 1);
  ck_assert_int_eq(s21_is_not_equal(dec1, dec2), 0);

  // new_test
  str_to_dec(
      "1001111110010000011011001100101110000011110001011000110110100100000011"
      "110101000001000100100011",
      &dec1, 12);
  str_to_dec(
      "1001111110010000011011001100101110000011110001011000110110100100000011"
      "110101000001000100100011",
      &dec2, 12);
  ck_assert_int_eq(s21_is_equal(dec1, dec2), 0);
  ck_assert_int_eq(s21_is_not_equal(dec1, dec2), 1);

  dec2.value_type = s21_INFINITY;
  ck_assert_int_eq(s21_is_equal(dec1, dec2), 1);
  ck_assert_int_eq(s21_is_not_equal(dec1, dec2), 0);

  dec1.value_type = s21_INFINITY;
  ck_assert_int_eq(s21_is_equal(dec1, dec2), 1);
  ck_assert_int_eq(s21_is_not_equal(dec1, dec2), 1);

  str_to_dec(
      "-1001111110010000011011001100101110000011110001011000110110100100000011"
      "110101000001000100100011",
      &dec1, 12);
  str_to_dec(
      "1001111110010000011011001100101110000011110001011000110110100100000011"
      "110101000001000100100011",
      &dec2, 12);

  ck_assert_int_eq(s21_is_equal(dec1, dec2), 1);
  ck_assert_int_eq(s21_is_not_equal(dec1, dec2), 0);

  str_to_dec(
      "-0000000000000000000000000000000000000000000000000000000000000000000000"
      "000000000000000000000000",
      &dec1, 12);
  str_to_dec(
      "0000000000000000000000000000000000000000000000000000000000000000000000"
      "000000000000000000000000",
      &dec2, 12);

  ck_assert_int_eq(s21_is_equal(dec1, dec2), 0);
  ck_assert_int_eq(s21_is_not_equal(dec1, dec2), 1);
}
END_TEST

START_TEST(greater_funcs_test) {
  s21_decimal dec1, dec2;
  init_dec(&dec1);
  dec1.value_type = s21_NORMAL_VALUE;
  init_dec(&dec2);
  dec2.value_type = s21_NORMAL_VALUE;
  dec1.bits[0] = 1325411;
  dec2.bits[0] = 1325411;
  dec1.bits[1] = 121;
  dec2.bits[1] = 121;
  dec1.bits[2] = 213;
  dec2.bits[2] = 213;

  // dec1 == dec2
  ck_assert_int_eq(s21_is_greater(dec1, dec2), 1);
  ck_assert_int_eq(s21_is_greater_or_equal(dec1, dec2), 0);

  dec2.bits[0] = 15;
  // dec1 > dec2
  ck_assert_int_eq(s21_is_greater(dec1, dec2), 0);
  ck_assert_int_eq(s21_is_greater_or_equal(dec1, dec2), 0);

  dec1.bits[3] += SIGN_MINUS;
  // dec1 < dec2
  ck_assert_int_eq(s21_is_greater(dec1, dec2), 1);
  ck_assert_int_eq(s21_is_greater_or_equal(dec1, dec2), 1);

  dec2.bits[3] += SIGN_MINUS;
  // dec1 < dec2
  ck_assert_int_eq(s21_is_greater(dec1, dec2), 1);
  ck_assert_int_eq(s21_is_greater_or_equal(dec1, dec2), 1);

  dec1.bits[3] = 0;
  // dec1 > dec2
  ck_assert_int_eq(s21_is_greater(dec1, dec2), 0);
  ck_assert_int_eq(s21_is_greater_or_equal(dec1, dec2), 0);

  str_to_dec("10000000000000000000000000000000", &dec1, 1);
  str_to_dec("-100000000000000000000000000000000", &dec2, 1);

  ck_assert_int_eq(s21_is_greater(dec1, dec2), 0);
  ck_assert_int_eq(s21_is_greater_or_equal(dec1, dec2), 0);

  // new test
  str_to_dec(
      "1001111110010000011011001100101110000011110001011000110110100100000011"
      "110101000001000100100011",
      &dec1, 12);
  str_to_dec(
      "1001111110010000011011001100101110000011110001011000110110100100000011"
      "110101000001000100100011",
      &dec2, 12);

  ck_assert_int_eq(s21_is_greater(dec1, dec2), 1);
  ck_assert_int_eq(s21_is_greater_or_equal(dec1, dec2), 0);

  str_to_dec(
      "1001111110010000011011001100101110000011110001011000110110100100000011"
      "110101000001000100100011",
      &dec2, 11);
  ck_assert_int_eq(s21_is_greater(dec1, dec2), 1);

  str_to_dec(
      "1001111110010000011011001100101110000011110001011000110110100100000011"
      "110101000001000100100011",
      &dec2, 13);
  ck_assert_int_eq(s21_is_greater(dec1, dec2), 0);

  str_to_dec(
      "-1001111110010000011011001100101110000011110001011000110110100100000011"
      "110101000001000100100011",
      &dec1, 12);
  str_to_dec(
      "1001111110010000011011001100101110000011110001011000110110100100000011"
      "110101000001000100100011",
      &dec2, 12);

  ck_assert_int_eq(s21_is_equal(dec1, dec2), 1);
  ck_assert_int_eq(s21_is_not_equal(dec1, dec2), 0);

  str_to_dec(
      "-0000000000000000000000000000000000000000000000000000000000000000000000"
      "000000000000000000000000",
      &dec1, 12);
  str_to_dec(
      "0000000000000000000000000000000000000000000000000000000000000000000000"
      "000000000000000000000000",
      &dec2, 12);

  ck_assert_int_eq(s21_is_equal(dec1, dec2), 0);
  ck_assert_int_eq(s21_is_not_equal(dec1, dec2), 1);

  dec1.value_type = s21_INFINITY;
  ck_assert_int_eq(s21_is_greater(dec1, dec2), 0);

  dec2.value_type = s21_NEGATIVE_INFINITY;
  ck_assert_int_eq(s21_is_greater(dec1, dec2), 0);

  dec2.value_type = s21_NORMAL_VALUE;
  ck_assert_int_eq(s21_is_greater(dec1, dec2), 0);
  dec2.value_type = s21_INFINITY;
  dec1.value_type = s21_NORMAL_VALUE;
  ck_assert_int_eq(s21_is_greater(dec1, dec2), 1);
}
END_TEST

START_TEST(lesser_funcs_test) {
  s21_decimal dec1, dec2;
  init_dec(&dec1);
  dec1.value_type = s21_NORMAL_VALUE;
  init_dec(&dec2);
  dec2.value_type = s21_NORMAL_VALUE;
  dec1.bits[0] = 1325411;
  dec2.bits[0] = 1325411;
  dec1.bits[1] = 121;
  dec2.bits[1] = 121;
  dec1.bits[2] = 213;
  dec2.bits[2] = 213;

  // dec1 == dec2
  ck_assert_int_eq(s21_is_less(dec1, dec2), 1);
  ck_assert_int_eq(s21_is_less_or_equal(dec1, dec2), 0);

  dec2.bits[0] = 15;
  // dec1 > dec2
  ck_assert_int_eq(s21_is_less(dec1, dec2), 1);
  ck_assert_int_eq(s21_is_less_or_equal(dec1, dec2), 1);

  dec1.bits[3] += SIGN_MINUS;
  // dec1 < dec2
  ck_assert_int_eq(s21_is_less(dec1, dec2), 0);
  ck_assert_int_eq(s21_is_less_or_equal(dec1, dec2), 0);

  dec2.bits[3] += SIGN_MINUS;
  // dec1 < dec2
  ck_assert_int_eq(s21_is_less(dec1, dec2), 0);
  ck_assert_int_eq(s21_is_less_or_equal(dec1, dec2), 0);

  dec1.bits[3] = 0;
  // dec1 > dec2
  ck_assert_int_eq(s21_is_less(dec1, dec2), 1);
  ck_assert_int_eq(s21_is_less_or_equal(dec1, dec2), 1);
}
END_TEST

START_TEST(eq_funcs_test_float_point) {
  s21_decimal dec1, dec2;
  // 5.201
  str_to_dec("1010001010001", &dec1, 3);
  // 5.201
  str_to_dec("1010001010001", &dec2, 3);
  ck_assert_int_eq(s21_is_equal(dec1, dec2), 0);
  ck_assert_int_eq(s21_is_not_equal(dec1, dec2), 1);
  // 5.201
  str_to_dec("1010001010001", &dec1, 3);
  // 52.01
  str_to_dec("1010001010001", &dec2, 2);
  ck_assert_int_eq(s21_is_equal(dec1, dec2), 1);
  ck_assert_int_eq(s21_is_not_equal(dec1, dec2), 0);

  // 174536166.053
  str_to_dec("10100010100011001010101000101010100101", &dec1, 3);
  // 174536.166053
  str_to_dec("10100010100011001010101000101010100101", &dec2, 6);
  ck_assert_int_eq(s21_is_equal(dec1, dec2), 1);
  ck_assert_int_eq(s21_is_not_equal(dec1, dec2), 0);

  // 174536.166053
  str_to_dec("10100010100011001010101000101010100101", &dec1, 6);
  // 174536.166053
  str_to_dec("10100010100011001010101000101010100101", &dec2, 6);
  ck_assert_int_eq(s21_is_equal(dec1, dec2), 0);
  ck_assert_int_eq(s21_is_not_equal(dec1, dec2), 1);

  // 0.00
  init_dec(&dec1);
  str_to_dec("", &dec1, 2);
  // 0
  init_dec(&dec2);
  str_to_dec("", &dec2, 0);
  ck_assert_int_eq(s21_is_equal(dec1, dec2), 0);
  ck_assert_int_eq(s21_is_not_equal(dec1, dec2), 1);
}
END_TEST

START_TEST(greater_test_float_point) {
  s21_decimal dec1, dec2;
  // 5.201
  str_to_dec("1010001010001", &dec1, 3);
  // 5.201
  str_to_dec("1010001010001", &dec2, 3);
  ck_assert_int_eq(s21_is_greater(dec1, dec2), 1);
  ck_assert_int_eq(s21_is_greater_or_equal(dec1, dec2), 0);
  // 5.201
  str_to_dec("1010001010001", &dec1, 3);
  // 52.01
  str_to_dec("1010001010001", &dec2, 2);
  ck_assert_int_eq(s21_is_greater(dec1, dec2), 1);
  ck_assert_int_eq(s21_is_greater_or_equal(dec1, dec2), 1);

  // 52.01
  str_to_dec("1010001010001", &dec1, 2);
  // 5.201
  str_to_dec("1010001010001", &dec2, 3);
  ck_assert_int_eq(s21_is_greater(dec1, dec2), 0);
  ck_assert_int_eq(s21_is_greater_or_equal(dec1, dec2), 0);

  // 174536166.053
  str_to_dec("10100010100011001010101000101010100101", &dec1, 3);
  // 174536.166053
  str_to_dec("10100010100011001010101000101010100101", &dec2, 6);
  ck_assert_int_eq(s21_is_greater(dec1, dec2), 0);
  ck_assert_int_eq(s21_is_greater_or_equal(dec1, dec2), 0);

  // 174536.166053
  str_to_dec("10100010100011001010101000101010100101", &dec1, 6);
  // 174536.166053
  str_to_dec("10100010100011001010101000101010100101", &dec2, 6);
  ck_assert_int_eq(s21_is_greater(dec1, dec2), 1);
  ck_assert_int_eq(s21_is_greater_or_equal(dec1, dec2), 0);

  // 563715.1
  str_to_dec("10101100000010000011111", &dec1, 1);
  // 174536.166053
  str_to_dec("1010", &dec2, 0);
  ck_assert_int_eq(s21_is_greater(dec1, dec2), 0);
  ck_assert_int_eq(s21_is_greater_or_equal(dec1, dec2), 0);

  str_to_dec("1111", &dec1, 1);
  // 174536.166053
  str_to_dec("1", &dec2, 0);
  ck_assert_int_eq(s21_is_greater(dec1, dec2), 0);
  ck_assert_int_eq(s21_is_greater_or_equal(dec1, dec2), 0);
}
END_TEST

START_TEST(mul) {
  s21_decimal res_dec, dec1, dec2, correct_result;
  init_dec(&res_dec), init_dec(&dec1), init_dec(&dec2),
      init_dec(&correct_result);
  // check NaN1
  str_to_dec("1", &dec1, 0), dec1.value_type = s21_NAN;
  str_to_dec("1", &dec2, 1);
  res_dec = s21_mul(dec1, dec2);
  correct_result.value_type = s21_NAN;
  ck_assert_int_eq(res_dec.value_type, correct_result.value_type);
  init_dec(&res_dec), init_dec(&dec1), init_dec(&dec2),
      init_dec(&correct_result);
  // check NaN2
  // 1e-28 * 0.1
  str_to_dec("1", &dec1, 0);
  str_to_dec("1", &dec2, 1), dec2.value_type = s21_NAN;
  res_dec = s21_mul(dec1, dec2);
  correct_result.value_type = s21_NAN;
  ck_assert_int_eq(res_dec.value_type, correct_result.value_type);
  init_dec(&res_dec), init_dec(&dec1), init_dec(&dec2),
      init_dec(&correct_result);
  // check infinity
  // 11228636363636363636363636363 * 10
  str_to_dec(
      "1001000100100000011100001111001111100110100111100111111110111111011001"
      "10"
      "1110100010111010001011",
      &dec1, 0);
  // 10
  str_to_dec("1010", &dec2, 0);
  res_dec = s21_mul(dec1, dec2);
  correct_result.value_type = s21_INFINITY;
  ck_assert_int_eq(res_dec.value_type, correct_result.value_type);
  init_dec(&res_dec), init_dec(&dec1), init_dec(&dec2),
      init_dec(&correct_result);
  // check negative infinity
  // 11228636363636363636363636363 * -10
  str_to_dec(
      "1001000100100000011100001111001111100110100111100111111110111111011001"
      "10"
      "1110100010111010001011",
      &dec1, 0);
  // 10
  str_to_dec("-1010", &dec2, 0);
  res_dec = s21_mul(dec1, dec2);
  correct_result.value_type = s21_NEGATIVE_INFINITY;
  ck_assert_int_eq(res_dec.value_type, correct_result.value_type);
  init_dec(&res_dec), init_dec(&dec1), init_dec(&dec2),
      init_dec(&correct_result);
  // check beyond factor scale
  // 1e-28 * 0.1
  str_to_dec("1", &dec1, 28);
  str_to_dec("1", &dec2, 1);
  res_dec = s21_mul(dec1, dec2);
  correct_result.value_type = s21_NORMAL_VALUE;
  ck_assert_int_eq(res_dec.value_type, correct_result.value_type);
  ck_assert_int_eq(s21_is_equal(res_dec, correct_result), 0);

  init_dec(&res_dec), init_dec(&dec1), init_dec(&dec2),
      init_dec(&correct_result);
  // check 1 * 1
  str_to_dec("1", &dec1, 0);
  str_to_dec("1", &dec2, 0);
  str_to_dec("1", &correct_result, 0);
  res_dec = s21_mul(dec1, dec2);
  ck_assert_int_eq(s21_is_equal(correct_result, res_dec), 0);
  init_dec(&res_dec), init_dec(&dec1), init_dec(&dec2),
      init_dec(&correct_result);
  // check 15845632502852867518708790067 * 5
  str_to_dec(
      "1100110011001100110011001100110011001100110011001100110011001100110011"
      "001100110011001100110011",
      &dec1, 0);
  str_to_dec("101", &dec2, 0);
  str_to_dec(
      "1111111111111111111111111111111111111111111111111111111111111111111111"
      "11111111111111111111111111",
      &correct_result, 0);
  res_dec = s21_mul(dec1, dec2);
  ck_assert_int_eq(s21_is_equal(correct_result, res_dec), 0);
  init_dec(&res_dec), init_dec(&dec1), init_dec(&dec2),
      init_dec(&correct_result);
}
END_TEST

START_TEST(mul_2) {
  s21_decimal dec1, dec2, result, correct_result;
  init_dec(&correct_result);
  init_dec(&result);
  init_dec(&dec1);
  init_dec(&dec2);

  str_to_dec("11001010", &dec1, 0);  // 202
  str_to_dec("11001010", &dec2, 0);
  result = s21_mul(dec1, dec2);
  //          1001111101100100
  str_to_dec("1001111101100100", &correct_result, 0);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);
  init_dec(&correct_result);
  init_dec(&result);
  init_dec(&dec1);
  init_dec(&dec2);

  // FAIL
  //  4
  str_to_dec("100", &dec1, 0);
  // 125
  str_to_dec("1111101", &dec2, 0);
  result = s21_mul(dec1, dec2);
  // 500
  str_to_dec("111110100", &correct_result, 0);

  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  // 123515
  str_to_dec("11110001001111011", &dec1, 0);
  // 11
  str_to_dec("1011", &dec2, 0);
  result = s21_mul(dec1, dec2);
  // 1358665
  str_to_dec("101001011101101001001", &correct_result, 0);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);
}
END_TEST

START_TEST(mul_3) {
  s21_decimal dec1, dec2, result, correct_result;
  init_dec(&correct_result);
  init_dec(&result);
  init_dec(&dec1);
  init_dec(&dec2);

  // 6796283919
  str_to_dec("110010101000101110001000000001111", &dec1, 0);
  // 202
  str_to_dec("11001010", &dec2, 0);
  // 1372849351638
  str_to_dec("10011111110100100001100101010101111010110", &correct_result, 0);
  result = s21_mul(dec1, dec2);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);
  init_dec(&correct_result);
  init_dec(&result);
  init_dec(&dec1);
  init_dec(&dec2);

  // 6796283919
  str_to_dec("110010101000101110001000000001111", &dec1, 6);
  // 202
  str_to_dec("11001010", &dec2, 0);
  // 1372849351638
  str_to_dec("10011111110100100001100101010101111010110", &correct_result, 6);
  result = s21_mul(dec1, dec2);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);
  init_dec(&correct_result);
  init_dec(&result);
  init_dec(&dec1);
  init_dec(&dec2);

  // 6796.283919
  str_to_dec("110010101000101110001000000001111", &dec1, 6);
  // 2.02
  str_to_dec("11001010", &dec2, 2);
  // 13728.49351638
  str_to_dec("10011111110100100001100101010101111010110", &correct_result, 8);
  result = s21_mul(dec1, dec2);

  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  // -54195595155
  str_to_dec("-110010011110010011110010011110010011", &dec1, 0);
  // 10
  str_to_dec("1010", &dec2, 0);
  // -541955951550
  str_to_dec("-111111000101111000101111000101110111110", &correct_result, 0);
  result = s21_mul(dec1, dec2);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  // -3724292940501892409235
  str_to_dec(
      "-110010011110010011110010011110010011110010011110010011110010011110010"
      "01"
      "1",
      &dec1, 0);
  // -135521
  str_to_dec("-100001000101100001", &dec2, 0);
  // 504719903589756961191936435
  str_to_dec(
      "1101000010111111010011000110011000110011000110011000110011000110011000"
      "1001100000110110011",
      &correct_result, 0);
  result = s21_mul(dec1, dec2);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  // -79,228,162,514,264,337,593,543,950,335
  str_to_dec(
      "-11111111111111111111111111111111"
      "11111111111111111111111111111111"
      "11111111111111111111111111111111",
      &dec1, 4);
  // 1000
  str_to_dec("1111101000", &dec2, 0);
  // 504719903589756961191936435
  str_to_dec(
      "-11111111111111111111111111111111"
      "11111111111111111111111111111111"
      "11111111111111111111111111111111",
      &correct_result, 1);
  result = s21_mul(dec1, dec2);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 1);
}
END_TEST

START_TEST(mul_4) {
  s21_decimal dec1, dec2, result, correct_result;
  init_dec(&correct_result);
  init_dec(&result);
  init_dec(&dec1);
  init_dec(&dec2);

  dec1.value_type = 1;
  // 135521
  str_to_dec("11111111111111111111111111111111", &dec2, 0);
  correct_result.value_type = 1;
  result = s21_mul(dec1, dec2);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 1);

  dec1.value_type = 2;
  // 135521
  str_to_dec("11111111111111111111111111111111", &dec2, 0);
  correct_result.value_type = 2;
  result = s21_mul(dec1, dec2);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 1);

  dec1.value_type = 1;
  // 135521
  str_to_dec("-11111111111111111111111111111111", &dec2, 0);
  correct_result.value_type = 2;
  result = s21_mul(dec1, dec2);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 1);
}
END_TEST

START_TEST(mul_uncommon_values) {
  s21_decimal dec1, dec2, result, correct_result;
  init_dec(&correct_result);
  init_dec(&correct_result);
  init_dec(&result);
  init_dec(&dec1);
  init_dec(&dec2);
  // 1.23456789123456789
  str_to_dec("110110110100110110100101110101100110100000101111100010101", &dec1,
             17);
  //  12345678912345678.9
  str_to_dec("110110110100110110100101110101100110100000101111100010101", &dec2,
             1);
  // 12345678912345680.134567891235
  str_to_dec(
      "100111111001000001101100110010111000001111000101100011011010010000001111"
      "0101000001000100100010",
      &correct_result, 12);
  result = s21_add(dec1, dec2);

  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  // #1
  // 112286.36363636363636363
  str_to_dec(
      "1001100000101101001010001000000000110111001011001101011"
      "1100010111010001011",
      &dec1, 17);
  // 4.16787847
  str_to_dec("11000110101111010110110000111", &dec2, 8);

  result = s21_add(dec1, dec2);

  // 112290.53151483363636363
  str_to_dec(
      "100110000010111010011010101011101100110011011000101000000010110100100010"
      "11",
      &correct_result, 17);

  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  // #2
  // 135521
  str_to_dec("100001000101100001", &dec1, 0);
  // 3724292940501892409235
  str_to_dec(
      "11001001111001001111001001111001001111001001111001"
      "0011110010011110010011",
      &dec2, 0);

  result = s21_add(dec1, dec2);

  // 3724292940501892544756
  str_to_dec(
      "11001001111001001111001001111001001111001001111001010001001110001111010"
      "0",
      &correct_result, 0);

  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  // #3
  // 0.0135521
  str_to_dec("100001000101100001", &dec1, 7);
  // 0.0000003724292940501892409235
  str_to_dec(
      "1100100111100100111100100111100100111100100111"
      "10010011110010011110010011",
      &dec2, 28);

  result = s21_add(dec1, dec2);

  // 0.013 55247 24292 94050 18924 09235
  str_to_dec(
      "111000000011010011110100000011001110011001100100011111010011000111011110"
      "010011110010011",
      &correct_result, 28);

  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  // #4
  // 24560730379421944653998624.602
  str_to_dec(
      "100111101011100001010001111010111000010100011110101110"
      "00010100011110101110000101000111101011010",
      &dec1, 3);
  // 31.7
  str_to_dec("100111101", &dec2, 1);

  result = s21_add(dec1, dec2);

  // 24560730379421944653998656.302
  str_to_dec(
      "100111101011100001010001111010111000010100011110101110000101000111101011"
      "10000110000101100101110",
      &correct_result, 3);

  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  // #5
  // 0.0000000000000000009
  str_to_dec("1001", &dec1, 19);
  // 0,000000000000000000000009
  str_to_dec("1001", &dec2, 24);

  result = s21_add(dec1, dec2);

  // 0.0000 00000 00000 00009 00009
  str_to_dec("11011011101110101001", &correct_result, 24);

  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  // #6
  // 0,0000000000000000000000095642
  str_to_dec("10111010110011010", &dec1, 28);
  // 0,0000000000000000000000112
  str_to_dec("1110000", &dec2, 25);

  result = s21_add(dec1, dec2);

  // 0.000 00000 00000 00000 00002 07642
  str_to_dec("110010101100011010", &correct_result, 28);

  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  // #7
  // 0,0000000000000000000000095642
  str_to_dec("10111010110011010", &dec1, 28);
  // 112000
  str_to_dec("11011010110000000", &dec2, 0);

  result = s21_add(dec1, dec2);

  // 112000.000 00000 00000 00000 00000
  str_to_dec(
      "100100001100000110110001000000100101111000010110011100010000111100000000"
      "0000000000000000000001",
      &correct_result, 23);

  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  // #8
  // 0,0000000000000000000000095642
  str_to_dec("10111010110011010", &dec1, 28);
  // 0.0000000000000000000000000002
  str_to_dec("10", &dec2, 28);

  result = s21_add(dec1, dec2);

  // 0.0000000000000000000000095644
  str_to_dec("10111010110011100", &correct_result, 28);

  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  // #9
  // 0,0000000000000000000000095642
  str_to_dec("10111010110011010", &dec1, 28);
  // 0.8539464285714285714285714286
  str_to_dec(
      "1101110010111101011011110011010000101100011010111110111"
      "11000010110011011101101101101101101110",
      &dec2, 28);

  result = s21_add(dec1, dec2);

  // 0.8539464285714285714285809928
  str_to_dec(
      "110111001011110101101111001101000010110001101011111011111000010110011011"
      "110000101000100001000",
      &correct_result, 28);

  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  // #10
  // 24560730379421944653998624.602
  str_to_dec(
      "100111101011100001010001111010111000010100011110101110000101000111101011"
      "10000101000111101011010",
      &dec1, 3);
  // 792281625142643375935439.50329
  str_to_dec(
      "111111111111111111111111111111111111111111111111111111111111111111111111"
      "111111111111111111111001",
      &dec2, 5);

  result = s21_add(dec1, dec2);

  // C #        25353012004564588029934064.105
  // full prec 25353012004564588029934064.10529
  // res       25353012004564588029934064.106
  str_to_dec(
      "101000111101011100001010001111010111000010100011110101110000101000111101"
      "01110000101000111101001",
      &correct_result, 3);

  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);
}
END_TEST

START_TEST(truncate_common_values) {
  s21_decimal dec, result, correct_result;
  init_dec(&result);
  // 677
  str_to_dec("1010100101", &dec, 0);
  str_to_dec("1010100101", &correct_result, 0);
  result = s21_truncate(dec);
  ck_assert_int_eq(s21_is_equal(result, correct_result), 0);

  // 67.7
  str_to_dec("1010100101", &dec, 1);
  //   s21_from_float_to_decimal(67.7, &dec);
  // 67
  str_to_dec("1000011", &correct_result, 0);
  result = s21_truncate(dec);
  ck_assert_int_eq(s21_is_equal(result, correct_result), 0);

  // -67.7
  str_to_dec("-1010100101", &dec, 1);
  // -67
  str_to_dec("-1000011", &correct_result, 0);
  result = s21_truncate(dec);
  ck_assert_int_eq(s21_is_equal(result, correct_result), 0);

  // 710579.877
  str_to_dec("101010010110101001011010100101", &dec, 3);
  // 710579
  str_to_dec("10101101011110110011", &correct_result, 0);
  result = s21_truncate(dec);
  ck_assert_int_eq(s21_is_equal(result, correct_result), 0);

  // 76297933.3938255525
  str_to_dec("101010010110101001011010100101101010010110101001011010100101",
             &dec, 10);
  // 76297933
  str_to_dec("100100011000011011011001101", &correct_result, 0);
  result = s21_truncate(dec);
  ck_assert_int_eq(s21_is_equal(result, correct_result), 0);

  // 819242.821697167591502157477
  str_to_dec(
      "1010100101101010010110101001011010100101101010010110101001011010100101"
      "10"
      "101001011010100101",
      &dec, 21);
  // 819242
  str_to_dec("11001000000000101010", &correct_result, 0);
  result = s21_truncate(dec);
  ck_assert_int_eq(s21_is_equal(result, correct_result), 0);

  // 819242821697167591502157477
  str_to_dec(
      "1010100101101010010110101001011010100101101010010110101001011010100101"
      "10"
      "101001011010100101",
      &dec, 0);
  // 819242821697167591502157477
  str_to_dec(
      "1010100101101010010110101001011010100101101010010110101001011010100101"
      "10"
      "101001011010100101",
      &correct_result, 0);
  result = s21_truncate(dec);
  ck_assert_int_eq(s21_is_equal(result, correct_result), 0);

  // 0.710579877
  str_to_dec("101010010110101001011010100101", &dec, 9);
  // 0
  init_dec(&correct_result);
  result = s21_truncate(dec);
  ck_assert_int_eq(s21_is_equal(result, correct_result), 0);
}

START_TEST(truncate_uncommon_values) {
  s21_decimal dec, result, correct_result;
  init_dec(&result);

  // 3541672354354167233.5414672354
  str_to_dec(
      "1110010011100000000011011101110011010010100110000111111011110111010010"
      "00"
      "00010000011101111100010",
      &dec, 10);
  // 3541672354354167233
  str_to_dec("11000100100110100011000011110111100000000110011111110111000001",
             &correct_result, 0);
  result = s21_truncate(dec);
  ck_assert_int_eq(s21_is_equal(result, correct_result), 0);

  // 7541.6723543541672335414672354
  str_to_dec(
      "1111001110101111010000000110011101100001111000000100100011111111111001"
      "00"
      "000010000011101111100010",
      &dec, 25);
  // 7541
  str_to_dec("1110101110101", &correct_result, 0);
  result = s21_truncate(dec);
  ck_assert_int_eq(s21_is_equal(result, correct_result), 0);
  // max_value = 792281625142643375935.43950335
  str_to_dec(
      "1111111111111111111111111111111111111111111111111111111111111111111111"
      "11"
      "111111111111111111111111",
      &dec, 8);
  result = s21_truncate(dec);
  // 792281625142643375935
  str_to_dec(
      "101010111100110001110111000100011000010001100001110011101111110011111"
      "1",
      &correct_result, 0);
  ck_assert_int_eq(s21_is_equal(result, correct_result), 0);
  str_to_dec(
      "1111111111111111111111111111111111111111111111111111111111111111111111"
      "11"
      "111111111111111111111111",
      &dec, 10);
  result = s21_truncate(dec);
  // 792281625142643375935
  str_to_dec(
      "101010111100110001110111000100011000010001100001110011101111110011111"
      "1",
      &correct_result, 0);
  ck_assert_int_eq(s21_is_equal(result, correct_result), 1);
}

START_TEST(round_dec) {
  s21_decimal dec, correct_result, res;
  init_dec(&dec), init_dec(&res), init_dec(&correct_result);

  // check 0 -> 0
  str_to_dec("0", &dec, 0);
  str_to_dec("0", &correct_result, 0);
  res = s21_round(dec);
  ck_assert_int_eq(s21_is_equal(res, correct_result), 0);
  init_dec(&res);

  // check 1 -> 1
  str_to_dec("1", &dec, 0);
  str_to_dec("1", &correct_result, 0);
  res = s21_round(dec);
  ck_assert_int_eq(s21_is_equal(res, correct_result), 0);
  init_dec(&res);

  // check 10.1 -> 10
  str_to_dec("1100101", &dec, 1);
  str_to_dec("1010", &correct_result, 0);
  res = s21_round(dec);
  ck_assert_int_eq(s21_is_equal(res, correct_result), 0);
  init_dec(&res);

  // check 10.5 -> 11
  str_to_dec("1101001", &dec, 1);
  str_to_dec("1011", &correct_result, 0);
  res = s21_round(dec);
  ck_assert_int_eq(s21_is_equal(res, correct_result), 0);

  // check -10.1 -> -10
  str_to_dec("-1100101", &dec, 1);
  str_to_dec("-1010", &correct_result, 0);
  res = s21_round(dec);
  ck_assert_int_eq(s21_is_equal(res, correct_result), 0);
  init_dec(&res);

  // check -10.5 -> -11
  str_to_dec("-1101001", &dec, 1);
  str_to_dec("-1011", &correct_result, 0);
  res = s21_round(dec);
  ck_assert_int_eq(s21_is_equal(res, correct_result), 0);

  // check max 7922816251426433759354395033.5 -> 7922816251426433759354395034
  str_to_dec(
      "1111111111111111111111111111111111111111111111111111111111111111111111"
      "11111111111111111111111111",
      &dec, 1);
  str_to_dec(
      "1100110011001100110011001100110011001100110011001100110011001100110011"
      "00110011001100110011010",
      &correct_result, 0);
  res = s21_round(dec);
  ck_assert_int_eq(s21_is_equal(res, correct_result), 0);
}
END_TEST

START_TEST(floor_dec) {
  s21_decimal dec, correct_result, res;
  init_dec(&dec), init_dec(&res), init_dec(&correct_result);

  // check 0 -> 0
  str_to_dec("0", &dec, 0);
  str_to_dec("0", &correct_result, 0);
  res = s21_floor(dec);
  ck_assert_int_eq(s21_is_equal(res, correct_result), 0);
  init_dec(&res);

  // check 1 -> 1
  str_to_dec("1", &dec, 0);
  str_to_dec("1", &correct_result, 0);
  res = s21_floor(dec);
  ck_assert_int_eq(s21_is_equal(res, correct_result), 0);
  init_dec(&res);

  // check 10.1 -> 10
  str_to_dec("1100101", &dec, 1);
  str_to_dec("1010", &correct_result, 0);
  res = s21_floor(dec);
  ck_assert_int_eq(s21_is_equal(res, correct_result), 0);
  init_dec(&res);

  // check 10.5 -> 10
  str_to_dec("1101001", &dec, 1);
  str_to_dec("1010", &correct_result, 0);
  res = s21_floor(dec);
  ck_assert_int_eq(s21_is_equal(res, correct_result), 0);

  // check -10.1 -> -11
  str_to_dec("-1100101", &dec, 1);
  str_to_dec("-1011", &correct_result, 0);
  res = s21_floor(dec);
  ck_assert_int_eq(s21_is_equal(res, correct_result), 0);
  init_dec(&res);

  // check -10.5 -> -11
  str_to_dec("-1101001", &dec, 1);
  str_to_dec("-1011", &correct_result, 0);
  res = s21_floor(dec);
  ck_assert_int_eq(s21_is_equal(res, correct_result), 0);

  // check max 7922816251426433759354395033.5 -> 7922816251426433759354395033
  str_to_dec(
      "1111111111111111111111111111111111111111111111111111111111111111111111"
      "11111111111111111111111111",
      &dec, 1);
  str_to_dec(
      "1100110011001100110011001100110011001100110011001100110011001100110011"
      "00110011001100110011001",
      &correct_result, 0);
  res = s21_floor(dec);
  ck_assert_int_eq(s21_is_equal(res, correct_result), 0);

  // check min -7922816251426433759354395033.5 ->
  // -7922816251426433759354395034
  str_to_dec(
      "-111111111111111111111111111111111111111111111111111111111111111111111"
      "111111111111111111111111111",
      &dec, 1);
  str_to_dec(
      "-110011001100110011001100110011001100110011001100110011001100110011001"
      "100110011001100110011010",
      &correct_result, 0);
  res = s21_floor(dec);
  ck_assert_int_eq(s21_is_equal(res, correct_result), 0);
}
END_TEST
START_TEST(add_norm) {
  s21_decimal dec1, dec2, result, correct_result;
  init_dec(&correct_result);
  init_dec(&correct_result);
  init_dec(&result);
  init_dec(&dec1);
  init_dec(&dec2);
  // 1.23456789123456789
  str_to_dec("110110110100110110100101110101100110100000101111100010101", &dec1,
             17);
  //  12345678912345678.9
  str_to_dec("110110110100110110100101110101100110100000101111100010101", &dec2,
             1);
  // 12345678912345680.134567891235
  str_to_dec(
      "100111111001000001101100110010111000001111000101100011011010010000001111"
      "0101000001000100100010",
      &correct_result, 12);
  result = s21_add(dec1, dec2);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);
  // #1
  // 112286.36363636363636363
  str_to_dec(
      "1001100000101101001010001000000000110111001011001101011"
      "1100010111010001011",
      &dec1, 17);
  // 4.16787847
  str_to_dec("11000110101111010110110000111", &dec2, 8);

  result = s21_add(dec1, dec2);

  // 112290.53151483363636363
  str_to_dec(
      "100110000010111010011010101011101100110011011000101000000010110100100010"
      "11",
      &correct_result, 17);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  // #2
  // 135521
  str_to_dec("100001000101100001", &dec1, 0);
  // 3724292940501892409235
  str_to_dec(
      "11001001111001001111001001111001001111001001111001"
      "0011110010011110010011",
      &dec2, 0);

  result = s21_add(dec1, dec2);

  // 3724292940501892544756
  str_to_dec(
      "11001001111001001111001001111001001111001001111001010001001110001111010"
      "0",
      &correct_result, 0);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  // #3
  // 0.0135521
  str_to_dec("100001000101100001", &dec1, 7);
  // 0.0000003724292940501892409235
  str_to_dec(
      "1100100111100100111100100111100100111100100111"
      "10010011110010011110010011",
      &dec2, 28);

  result = s21_add(dec1, dec2);

  // 0.013 55247 24292 94050 18924 09235
  str_to_dec(
      "111000000011010011110100000011001110011001100100011111010011000111011110"
      "010011110010011",
      &correct_result, 28);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  // #4
  // 24560730379421944653998624.602
  str_to_dec(
      "100111101011100001010001111010111000010100011110101110"
      "00010100011110101110000101000111101011010",
      &dec1, 3);
  // 31.7
  str_to_dec("100111101", &dec2, 1);

  result = s21_add(dec1, dec2);

  // 24560730379421944653998656.302
  str_to_dec(
      "100111101011100001010001111010111000010100011110101110000101000111101011"
      "10000110000101100101110",
      &correct_result, 3);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  // #5
  // 0.0000000000000000009
  str_to_dec("1001", &dec1, 19);
  // 0,000000000000000000000009
  str_to_dec("1001", &dec2, 24);

  result = s21_add(dec1, dec2);

  // 0.0000 00000 00000 00009 00009
  str_to_dec("11011011101110101001", &correct_result, 24);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  // #6
  // 0,0000000000000000000000095642
  str_to_dec("10111010110011010", &dec1, 28);
  // 0,0000000000000000000000112
  str_to_dec("1110000", &dec2, 25);

  result = s21_add(dec1, dec2);

  // 0.000 00000 00000 00000 00002 07642
  str_to_dec("110010101100011010", &correct_result, 28);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);
  // #7
  // 0,0000000000000000000000095642
  str_to_dec("10111010110011010", &dec1, 28);
  // 112000
  str_to_dec("11011010110000000", &dec2, 0);

  result = s21_add(dec1, dec2);

  // 112000.000 00000 00000 00000 00000
  str_to_dec(
      "100100001100000110110001000000100101111000010110011100010000111100000000"
      "0000000000000000000001",
      &correct_result, 23);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  // #8
  // 0,0000000000000000000000095642
  str_to_dec("10111010110011010", &dec1, 28);
  // 0.0000000000000000000000000002
  str_to_dec("10", &dec2, 28);

  result = s21_add(dec1, dec2);

  // 0.0000000000000000000000095644
  str_to_dec("10111010110011100", &correct_result, 28);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  // #9
  // 0,0000000000000000000000095642
  str_to_dec("10111010110011010", &dec1, 28);
  // 0.8539464285714285714285714286
  str_to_dec(
      "1101110010111101011011110011010000101100011010111110111"
      "11000010110011011101101101101101101110",
      &dec2, 28);

  result = s21_add(dec1, dec2);

  // 0.8539464285714285714285809928
  str_to_dec(
      "110111001011110101101111001101000010110001101011111011111000010110011011"
      "110000101000100001000",
      &correct_result, 28);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  // #10
  // 24560730379421944653998624.602
  str_to_dec(
      "100111101011100001010001111010111000010100011110101110000101000111101011"
      "10000101000111101011010",
      &dec1, 3);
  // 792281625142643375935439.50329
  str_to_dec(
      "111111111111111111111111111111111111111111111111111111111111111111111111"
      "111111111111111111111001",
      &dec2, 5);

  result = s21_add(dec1, dec2);

  // C #        25353012004564588029934064.105
  // full prec 25353012004564588029934064.10529
  // res       25353012004564588029934064.106
  str_to_dec(
      "101000111101011100001010001111010111000010100011110101110000101000111101"
      "01110000101000111101001",
      &correct_result, 3);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);
}
END_TEST

START_TEST(special_values) {
  s21_decimal dec1, dec2, result, correct_result;
  init_dec(&correct_result);
  init_dec(&result);
  init_dec(&dec1);
  init_dec(&dec2);

  dec1.value_type = s21_INFINITY;
  // 135521
  str_to_dec("11111111111111111111111111111111", &dec2, 0);

  result = s21_add(dec1, dec2);
  ck_assert_int_eq(result.value_type, s21_INFINITY);
  init_dec(&result);

  dec1.value_type = s21_NEGATIVE_INFINITY;
  // 135521
  str_to_dec("11111111111111111111111111111111", &dec2, 0);
  correct_result.value_type = 2;
  result = s21_add(dec1, dec2);
  ck_assert_int_eq(result.value_type, s21_NEGATIVE_INFINITY);
}
END_TEST
START_TEST(sub_normal_test_integer) {
  s21_decimal dec1, dec2, result, correct_result;
  init_dec(&correct_result);
  init_dec(&result);
  init_dec(&dec1);
  init_dec(&dec2);
  str_to_dec("11001010", &dec1, 0);
  str_to_dec("11001010", &dec2, 0);
  result = s21_sub(dec1, dec2);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  str_to_dec("11000011010100000", &dec1, 0);            // 100000
  str_to_dec("1111", &dec2, 0);                         // 15
  str_to_dec("11000011010010001", &correct_result, 0);  // 99985
  result = s21_sub(dec1, dec2);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  str_to_dec("1111", &dec1, 0);                          // 15
  str_to_dec("11000011010100000", &dec2, 0);             // 100000
  str_to_dec("-11000011010010001", &correct_result, 0);  // -99985
  result = s21_sub(dec1, dec2);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  // 1237576213581
  str_to_dec("10010000000100101010010100110010001001101", &dec1, 0);
  // 1
  str_to_dec("1", &dec2, 0);
  // 1237576213580
  str_to_dec("10010000000100101010010100110010001001100", &correct_result, 0);
  result = s21_sub(dec1, dec2);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  str_to_dec("-1111", &dec1, 0);                        // -15
  str_to_dec("-11000011010100000", &dec2, 0);           // -100000
  str_to_dec("11000011010010001", &correct_result, 0);  // 99985
  result = s21_sub(dec1, dec2);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  // -0.2
  str_to_dec("-10", &dec1, 1);
  // -0.0000001
  str_to_dec("-1", &dec2, 7);
  // -0.1999999
  str_to_dec("-111101000010001111111", &correct_result, 7);
  result = s21_sub(dec1, dec2);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  str_to_dec("11010000000100101010010100110010001001101", &dec1, 0);
  // 1
  str_to_dec("1010000000100101010010100110010001001100", &dec2, 0);
  // 1237576213580
  str_to_dec("10000000000000000000000000000000000000001", &correct_result, 0);
  result = s21_sub(dec1, dec2);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);
  // 49155195229197460557
  str_to_dec(
      "101010101000101010010101011010000000100101010010100110010001001101",
      &dec1, 0);
  // 687820399692
  str_to_dec("1010000000100101010010100110010001001100", &dec2, 0);
  // 49155194541377060865
  str_to_dec(
      "101010101000101010010101010000000000000000000000000000000000000001",
      &correct_result, 0);
  result = s21_sub(dec1, dec2);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);

  str_to_dec("101010100101010101111010101001010", &dec1, 0);
  // 1
  str_to_dec("11001000000000000000000000000000", &dec2, 0);
  // 1237576213580
  str_to_dec("10001100101010101111010101001010", &correct_result, 0);
  result = s21_sub(dec1, dec2);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);
}
END_TEST

START_TEST(sub_uncommon_values) {
  s21_decimal dec1, dec2, result, correct_result;
  // 79228162514264337593543950330 - 49517601571415210995964968960
  str_to_dec(
      "1111111111111111111111111111111111111111111111111111111111111111111111"
      "11"
      "111111111111111111111010",
      &dec1, 0);
  str_to_dec(
      "1010000000000000000000000000000000000000000000000000000000000000000000"
      "00"
      "000000000000000000000000",
      &dec2, 0);
  init_dec(&result);
  result = s21_sub(dec1, dec2);
  // 29710560942849126597578981370
  str_to_dec(
      "1011111111111111111111111111111111111111111111111111111111111111111111"
      "11"
      "11111111111111111111010",
      &correct_result, 0);
  ck_assert_int_eq(s21_is_equal(correct_result, result), 0);
}

START_TEST(s21_round_Check) {
  s21_decimal dst1, dst2;
  float statMeanArr[20] = {2147483647,
                           -2147483647,
                           0,
                           0.000001,
                           123123123123.123123123,
                           2100.00201,
                           -123,
                           1234.000000,
                           -0.0002,
                           -123.43422,
                           -11111.509234,
                           00000.13,
                           200000001.1231231,
                           123.43,
                           -98765.4321,
                           -1,
                           -000000000123,
                           4234234,
                           -1.534534534534534534534,
                           -545324.321312};

  float statMeanArrRes[20] = {
      2147483647, -2147483647,   0,         0,   123123123123,
      2100,       -123,          1234,      -0,  -123,
      -11112,     00000,         200000001, 123, -98765,
      -1,         -000000000123, 4234234,   -2,  -545324};

  s21_clean(&dst1);
  s21_clean(&dst2);

  for (int i = 0; i < 20; i++) {
    s21_from_float_to_decimal((statMeanArr[i]), &dst1);
    s21_from_float_to_decimal((statMeanArrRes[i]), &dst2);

    dst1 = s21_round(dst1);

    ck_assert_int_eq(s21_is_equal(dst1, dst2), 0);
  }
}
END_TEST

START_TEST(s21_truncate_Check) {
  s21_decimal dst1, dst2;
  float statMeanArr[20] = {2147483647,
                           -2147483647,
                           0,
                           0.000001,
                           123123123123.123123123,
                           2100.00201,
                           -123,
                           1234.000000,
                           -0.0002,
                           -123.43422,
                           -11111.509234,
                           00000.13,
                           200000001.1231231,
                           123.43,
                           -98765.4321,
                           -1,
                           -000000000123,
                           4234234,
                           -1.534534534534534534534,
                           -545324.321312};

  float statMeanArrRes[20] = {
      2147483647, -2147483647,   0,         0,   123123123123,
      2100,       -123,          1234,      -0,  -123,
      -11111,     00000,         200000001, 123, -98765,
      -1,         -000000000123, 4234234,   -1,  -545324};

  s21_clean(&dst1);
  s21_clean(&dst2);

  for (int i = 0; i < 20; i++) {
    s21_from_float_to_decimal((statMeanArr[i]), &dst1);
    s21_from_float_to_decimal((statMeanArrRes[i]), &dst2);

    dst1 = s21_truncate(dst1);

    ck_assert_int_eq(s21_is_equal(dst1, dst2), 0);
  }
}
END_TEST

START_TEST(s21_floor_Check) {
  s21_decimal dst1, dst2;
  float statMeanArr[20] = {2147483647,
                           -2147483647,
                           0,
                           0.000001,
                           123123123123.123123123,
                           2100.00201,
                           -123,
                           1234.000000,
                           -0.0002,
                           -123.43422,
                           -11111.509234,
                           00000.13,
                           200000001.1231231,
                           123.43,
                           -98765.4321,
                           -1,
                           -000000000123,
                           4234234,
                           -1.534534534534534534534,
                           -545324.321312};

  float statMeanArrRes[20] = {
      2147483647, -2147483647,   0,         0,   123123123123,
      2100,       -123,          1234,      -1,  -124,
      -11112,     00000,         200000001, 123, -98766,
      -1,         -000000000123, 4234234,   -2,  -545325};

  s21_clean(&dst1);
  s21_clean(&dst2);

  for (int i = 0; i < 20; i++) {
    s21_from_float_to_decimal((statMeanArr[i]), &dst1);
    s21_from_float_to_decimal((statMeanArrRes[i]), &dst2);

    dst1 = s21_floor(dst1);

    ck_assert_int_eq(s21_is_equal(dst1, dst2), 0);
  }
}
END_TEST

START_TEST(s21_negate_Check) {
  s21_decimal dst1, dst2;
  float statMeanArr[20] = {2147483647,
                           -2147483647,
                           0,
                           0.000001,
                           123123123123.123123123,
                           2100.00201,
                           -123,
                           1234.000000,
                           -0.0002,
                           -123.43422,
                           -11111.509234,
                           00000.13,
                           200000001.1231231,
                           123.43,
                           -98765.4321,
                           -1,
                           -000000000123,
                           4234234,
                           -1.534534534534534534534,
                           -545324.321312};

  float statMeanArrRes[20] = {-2147483647,
                              2147483647,
                              -0,
                              -0.000001,
                              -123123123123.123123123,
                              -2100.00201,
                              123,
                              -1234.000000,
                              0.0002,
                              123.43422,
                              11111.509234,
                              -00000.13,
                              -200000001.1231231,
                              -123.43,
                              98765.4321,
                              1,
                              000000000123,
                              -4234234,
                              1.534534534534534534534,
                              545324.321312};

  s21_clean(&dst1);
  s21_clean(&dst2);

  for (int i = 0; i < 20; i++) {
    s21_from_float_to_decimal((statMeanArr[i]), &dst1);
    s21_from_float_to_decimal((statMeanArrRes[i]), &dst2);

    dst1 = s21_negate(dst1);

    ck_assert_int_eq(s21_is_equal(dst1, dst2), 0);
  }
}
END_TEST

int main(void) {
  Suite *s1 = suite_create("Core");
  TCase *tc1_1 = tcase_create("Core");
  SRunner *sr = srunner_create(s1);
  int nf;

  suite_add_tcase(s1, tc1_1);

  // conv
  tcase_add_test(tc1_1, from_int_to_dec);
  tcase_add_test(tc1_1, from_float_to_dec);
  tcase_add_test(tc1_1, from_dec_to_int);
  tcase_add_test(tc1_1, from_dec_to_float);

  // div / mod
  tcase_add_test(tc1_1, div_common_values);
  tcase_add_test(tc1_1, div_uncommon_values);
  tcase_add_test(tc1_1, mod_common_values);
  tcase_add_test(tc1_1, mod_uncommon_values);

  // compare
  tcase_add_test(tc1_1, eq_funcs_test);
  tcase_add_test(tc1_1, greater_funcs_test);
  tcase_add_test(tc1_1, lesser_funcs_test);
  tcase_add_test(tc1_1, eq_funcs_test_float_point);
  tcase_add_test(tc1_1, greater_test_float_point);

  // mul
  tcase_add_test(tc1_1, mul);
  tcase_add_test(tc1_1, mul_2);
  tcase_add_test(tc1_1, mul_3);
  tcase_add_test(tc1_1, mul_4);
  tcase_add_test(tc1_1, mul_uncommon_values);

  // misc_funcs
  tcase_add_test(tc1_1, truncate_common_values);
  tcase_add_test(tc1_1, truncate_uncommon_values);
  tcase_add_test(tc1_1, round_dec);
  tcase_add_test(tc1_1, floor_dec);

  // add
  tcase_add_test(tc1_1, add_norm);
  tcase_add_test(tc1_1, special_values);

  // sub
  tcase_add_test(tc1_1, sub_normal_test_integer);
  tcase_add_test(tc1_1, sub_uncommon_values);

  tcase_add_test(tc1_1, s21_floor_Check);
  tcase_add_test(tc1_1, s21_round_Check);
  tcase_add_test(tc1_1, s21_truncate_Check);
  tcase_add_test(tc1_1, s21_negate_Check);

  srunner_run_all(sr, CK_ENV);
  nf = srunner_ntests_failed(sr);
  srunner_free(sr);

  return nf == 0 ? 0 : 1;
}
